replicaCount: 1
fullnameOverride: "midr-bff"
image:
  repository: harbor.zello.space/extrata/midr-bff
  tag: ""
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: harbor-zello

deployments:
  command: ["/bin/sh"]
  args: ["-c", "export TZ=America/Sao_Paulo && npm run start:prd"]

nameOverride: ""

ingress:
  enabled: true
  className: "kong"
  annotations: {}
  hosts:
    - host: api.extrata.com.br
      paths:
        - path: /midr-bff
          pathType: ImplementationSpecific
  tls: {}

livenessProbe:
  failureThreshold: 3
  httpGet:
    path: /midr-bff/health
    port: 3000
    scheme: HTTP
  initialDelaySeconds: 180
  periodSeconds: 2
  successThreshold: 1
  timeoutSeconds: 2

readinessProbe:
  failureThreshold: 3
  httpGet:
    path: /midr-bff/health
    port: 3000
    scheme: HTTP
  initialDelaySeconds: 180
  periodSeconds: 2
  successThreshold: 2
  timeoutSeconds: 2

virtualService:
  enabled: false
  hosts: "midr-bff-hlg.api.zello.services"
  prefix: "/"

resources:
  limits:
    cpu: 2000m
    memory: 4Gi
  requests:
    cpu: 100m
    memory: 100Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

ExternalSecret:
  enable: true
  name: midr-bff-vault
  namespace: extrata
  secretStoreRef:
    name: cluster-secret-store-vault
    kind: ClusterSecretStore
  refreshInterval: "2m"
  target:
    name: midr-bff-vault
  dataFrom:
    key: prd/midr-bff/

service:
  type: ClusterIP
  port: 3000